language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_SECRET_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: "A1"
  env: "A1-env"
  bucket_name: "swe1-app"
  on:
    branch: main
