language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$ACCESSKEYID"
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-1"
  app: "A1"
  env: "Django-1"
  bucket_name: "swe1-app"
