language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=1"
  secret_access_key:
    secure: "Encypted <secret-access-key>=1"
  region: "us-east-1"
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "the-target-S3-bucket"
