language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=$ACCESSKEYID"
  secret_access_key:
    secure: "Encypted <secret-access-key>=$SECRETACCESSKEY"
  region: "us-east-1"
  app: "Django-app"
  env: "Django-1"
  bucket_name: "the-target-S3-bucket"
