language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
script:
  - python manage.py test
  - python -m black --check
  - python -m flake8 --max-line-length=91
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_SECRET_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: "mysite"
  env: "django-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-411926377614"
  on:
    branch: main
